### ISSUE TITLE
background of the title screen and the text Mince meat 2 are missing

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#9] opened 2024-05-03 18:15 UTC
the background of the title screen is just black and the text that appears over Sal is gone

**Comment by uthw** [comment] 2024-05-03 18:34
I can't reproduce this in the current state of the modpack. Can you try opening a fresh install of Mincemeat 2 and see if it's still a black screen? Though in the past Saul could be replaced with a black screen when the game fails to load sometimes.

**Comment by uthw** [comment] 2024-05-04 16:53
Fixed in 0.2.1

**Closed by uthw** 2024-05-04 16:53 UTC
