### ISSUE TITLE
Money system

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#74] opened 2024-08-04 01:41 UTC
One of the few things that are in mincemeat 1 but not 2 is the money system. I like the system since it gives some incentive to quests apart from progression or just the fun of finishing them. I think a system could be made with physical or with a scoreboard command somewhat easily.

**Comment by uthw** [comment] 2024-08-06 03:30
Duplicate of #24, I will close this and leave that one open until I add a money system

**Closed by uthw** 2024-08-06 03:30 UTC
Labels: Planned
